from setuptools import setup, find_packages

version = '0.1'

setup(
    name = 'zojax.cms',
    version = version,
    description = "Zojax CMS",
    author = 'Dmitry Suvorov',
    author_email='suvdim@gmail.com',
    url = 'http://www.zojax.com',
    packages = find_packages('src'),
    package_dir = {'':'src'},
    namespace_packages = ['zojax'],
    include_package_data = True,
    license='',
    zip_safe = False,
    install_requires=[
        'setuptools',
        'simplejson',
        'rwproperty',
        'zope.app.zcmlfiles',
        'zope.app.twisted',
        'zope.app.securitypolicy',
        'zope.app.security',
        'zope.app.catalog',
        'zope.app.cache',
        'zope.app.file',
        'zope.app.preference',
        'zope.app.apidoc',
        'zope.app.traversing',
        'zope.sendmail',
        'zope.error',
        'zc.configuration',
        'z3c.configurator',
        'z3c.autoinclude',

        'zojax.layout',
        'zojax.layoutform',
        'zojax.portlet',
        'zojax.pageelement',
        'zojax.statusmessage',
        'zojax.resource',
        'zojax.resourcepackage',

        'zojax.portal',
        'zojax.jquery.corner',

        'zojax.portlets.googleads',
        'zojax.portlets.amazonwidget',
        'zojax.portlets.login',
        'zojax.portlets.recent',
        'zojax.portlets.navigation',
        'zojax.portlets.htmlsource',
        'zojax.portlets.container',
        'zojax.portlets.imagerotator',

        'zojax.widget.tinymce',
        'zojax.widget.extjsdate',
        'zojax.widget.extjseditor',
        'zojax.ui.googleanalytics',
        'zojax.ui.breadcrumbs',
        'zojax.ui.portaltabs',
        'zojax.ui.searching',

        'zojax.persistent.fields',
        'zojax.principal.profile',
        'zojax.principal.invite',
        'zojax.principal.ban',

        'zojax.blogger',
        'zojax.forum',
        'zojax.photoalbum',
        'zojax.askexpert',
        'zojax.error',
        'zojax.profiler',

        'zojax.personal.content',
        'zojax.personal.space',
        'zojax.personal.blogger',
        'zojax.personal.bar',
        'zojax.personal.invitation',
        'zojax.personal.favorites',
        'zojax.personal.tagging',

        'zojax.content.discussion',
        'zojax.content.browser',
        'quick.theme.sample',

        'zojax.ui.publicwidgets',
        'zojax.seo',
        'zojax.widget.dropdowndate',
        'zojax.site',
        'zojax.content.featured',
        'zojax.project',
        'zojax.company',
        'zojax.content.urlmapper',
        'zojax.undo',
        'zojax.poll',
        'zojax.formatter',
    ],
    extras_require = dict(
        test = [
            'zope.app.security',
            'zope.app.securitypolicy',
            'zope.app.testing',
            'zope.app.zcmlfiles',
            'zope.component',
            'zope.securitypolicy',
            'zope.testbrowser',
            'zope.testing',

            'zojax.autoinclude',
            'zojax.security',
        ]
    ),
    entry_points = """
        # -*- Entry points: -*-
        """,
    dependency_links = ['http://download.zope.org/distribution'],
)
